from fastapi import APIRouter, Response, Request, Path, Query
from fastapi.responses import JSONResponse
from app.libs.chains import (
    Context,
    ProviderSelectionHandler,
    ToolExtractionHandler,
    ToolResponseHandler,
    FallbackHandler,
)
from typing import Optional

router = APIRouter()


# Add get endpoint for /openai/v1 and print request body
@router.get("/{provider}/v1")
async def get_openai_v1(
    response: Response, provider: str = Path(..., title="Provider")
) -> JSONResponse:
    return JSONResponse(content={"message": f"GET request to {provider} v1"})


@router.post("/{provider}/v1/chat/completions")
async def post_chat_completions(
    request: Request,
    provider: str = Path(..., title="Provider")
) -> JSONResponse:
    try:
        if not provider:
            provider = "openai"

        if not ProviderSelectionHandler.provider_exists(provider):
            return JSONResponse(content={"error": "Invalid provider"}, status_code=400)

        # Extract the API token and body from the request
        api_token = request.headers.get("Authorization").split("Bearer ")[1]
        body = await request.json()

        # Initialize the context with request details
        context = Context(request, provider, body)
        context.api_token = (
            api_token  # Adding the API token to the context for use in handlers
        )

        # Initialize and link the handlers
        provider_selection_handler = ProviderSelectionHandler()
        tool_extraction_handler = ToolExtractionHandler()
        tool_response_handler = ToolResponseHandler()
        fallback_handler = FallbackHandler()

        # Set up the chain of responsibility
        provider_selection_handler.set_next(tool_extraction_handler).set_next(
            tool_response_handler
        ).set_next(fallback_handler)

        # Execute the chain with the initial context
        response = await provider_selection_handler.handle(context)

        # Return the response generated by the handlers
        return response
    except Exception as e:
        print(f"Error processing the request: {e}")
        return JSONResponse(
            content={"error": "An unexpected error occurred"}, status_code=500
        )
